#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: x-wrt-master=x86_64

on: 
  release:
    types: [published]
  push:
    branches:
      - master
  schedule:
    - cron: 0 8 * * 5
  watch:
    types: [started]


jobs:
  build:
    name: Build x-wrt firmware
    runs-on: ubuntu-18.04

jobs:
  build:
    name: Build x-wrt firmware
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      run: git clone --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git

    - name: Update feeds
      run: cd x-wrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd x-wrt && ./scripts/feeds install -a

    - name: Building
      run: |
        cp *.sh x-wrt/
        cp release.tag x-wrt/
        cd x-wrt
        echo -e "$(nproc) thread build."
        TARGET=x86_64 sh build.sh $(nproc)

    - name : Upload make.log if failure
      uses: actions/upload-artifact@master
      if: failure()
      with:
        name: build-failure-log
        path: make.log

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: x-wrt-master=x86_64
        path: x-wrt/rom
